# Exported from Render on 2024-03-26T13:02:07Z
services:
- type: web
  name: JWT-BusManager
  runtime: node
  repo: https://github.com/S05K/JWT
  branch: jwt_branch
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: ./bin/render-build.sh
  startCommand: bundle exec rails s
version: "1"